# Generated by Django 5.1.4 on 2026-03-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_comentario_options_alter_comentario_coment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='clave')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario contacto',
                'verbose_name_plural': 'Comentario contactos',
                'ordering': ['-created'],
            },
        ),
    ]
