# Generated by Django 5.1.4 on 2026-03-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_comentariocontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariocontacto',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario contacto', 'verbose_name_plural': 'Comentarios contactos'},
        ),
        migrations.AlterField(
            model_name='comentariocontacto',
            name='mensaje',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
